### ISSUE TITLE
Add links / references for all packages and functions

### ISSUE THREAD

**Issue by teofiln** [discindo/booklet#2]
probably links in the text is more important than endnote references..

**Comment by KshitizDayal** [comment]
Hey!
Can you please elaborate what to do to fix this issue?.

**Comment by novica** [comment]
Hi @KshitizDayal Thanks for showing interest in this issue. This is a text in Macedonian and the issues are language specific, i.e. you need to understand Macedonian to make meaningful edits.

**Comment by KshitizDayal** [comment]
Ooh okay. Thanks for letting me know. Sorry I don't understand Macedonian so i can't contribute.
